const fs = require('node:fs');
const path = require('node:path');
const { withNativeFederation, shareAll } = require('@angular-architects/native-federation/config');

// federation.config.json is auto-generated by `nexus-build` from @NexusRemote
// decorators in src/. This file just reads it and wires it into Native Federation.
const jsonPath = path.join(__dirname, 'federation.config.json');
if (!fs.existsSync(jsonPath)) {
  throw new Error(
    `federation.config.json not found at ${jsonPath}. ` +
    `Run \`nexus-build\` (or \`npm run prebuild\`) to generate it from your @NexusRemote decorators.`,
  );
}
const json = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));

module.exports = withNativeFederation({
  name: json.name,
  exposes: json.exposes,
  shared: {
    ...shareAll({ singleton: true, strictVersion: true, requiredVersion: 'auto' }),
  },
  skip: [
    'rxjs/ajax',
    'rxjs/fetch',
    'rxjs/testing',
    'rxjs/webSocket',
    '@bimo-dk/nexus-build',
  ],
});
